INSERT INTO STUDENT("SID", "SNAME", "SAGE") VALUES(1, 'ABHI', 21);
INSERT INTO STUDENT("SID", "SNAME", "SAGE") VALUES(2, 'RAM', 28);
INSERT INTO STUDENT("SID", "SNAME", "SAGE") VALUES(3, 'SHAYAM', 22);
INSERT INTO STUDENT("SID", "SNAME", "SAGE") VALUES(4, 'DHONI', 29);
INSERT INTO STUDENT("SID", "SNAME", "SAGE") VALUES(5, 'KING', 20);
--OR WE CAN JUST ADD 

INSERT INTO STUDENT("SID", "SNAME", "SAGE") VALUES
(6, 'RAJU', 54),
(7, 'SONU', 34),
(8, 'RAJ', 64);
